// File generated by FlutterFire CLI (edited to load secrets from lib/secrets.dart).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Secrets.webApiKey,
    appId: Secrets.webAppId,
    messagingSenderId: Secrets.webSenderId,
    projectId: Secrets.webProjectId,
    authDomain: Secrets.webAuthDomain,
    databaseURL: Secrets.webDatabaseUrl,
    storageBucket: Secrets.webStorageBucket,
    measurementId: Secrets.webMeasurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Secrets.androidApiKey,
    appId: Secrets.androidAppId,
    messagingSenderId: Secrets.androidSenderId,
    projectId: Secrets.androidProjectId,
    databaseURL: Secrets.androidDatabaseUrl,
    storageBucket: Secrets.androidStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Secrets.iosApiKey,
    appId: Secrets.iosAppId,
    messagingSenderId: Secrets.iosSenderId,
    projectId: Secrets.iosProjectId,
    databaseURL: Secrets.iosDatabaseUrl,
    storageBucket: Secrets.iosStorageBucket,
    iosBundleId: Secrets.iosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Secrets.macosApiKey,
    appId: Secrets.macosAppId,
    messagingSenderId: Secrets.macosSenderId,
    projectId: Secrets.macosProjectId,
    databaseURL: Secrets.macosDatabaseUrl,
    storageBucket: Secrets.macosStorageBucket,
    iosBundleId: Secrets.macosBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Secrets.windowsApiKey,
    appId: Secrets.windowsAppId,
    messagingSenderId: Secrets.windowsSenderId,
    projectId: Secrets.windowsProjectId,
    authDomain: Secrets.windowsAuthDomain,
    databaseURL: Secrets.windowsDatabaseUrl,
    storageBucket: Secrets.windowsStorageBucket,
    measurementId: Secrets.windowsMeasurementId,
  );
}
